-- ==========================================================
-- EstateHub — Seed & Sample Data (MySQL 8)
-- All demo user passwords are: Password123!
-- BCrypt hash for 'Password123!' -> $2a$10$wE1oG1tq7mN0uXk7v0mUreWvFj1H7G8vO1sK1h7v8w9v1q1b1q1u
-- (Actual standard BCrypt: $2a$10$eACCYoNOHEqgkVE8aGY2... generated by PasswordUtil)
-- ==========================================================



-- 1. SEED CATEGORIES
INSERT INTO property_categories (category_id, name, slug, description, icon_class) VALUES
(1, 'Apartment', 'apartment', 'Modern multi-family residential units with premium amenities', 'bi-building'),
(2, 'Luxury Villa', 'villa', 'Standalone grand estates with private gardens, pools, and lawns', 'bi-house-heart'),
(3, 'Independent House', 'house', 'Private residential houses and duplex bungalows', 'bi-house-door'),
(4, 'Commercial Office', 'office', 'Prime corporate offices, business centers, and IT parks', 'bi-briefcase'),
(5, 'Retail Shop', 'shop', 'High-footfall storefronts and commercial retail spaces', 'bi-shop'),
(6, 'Residential Plot', 'plot', 'Clear-title land parcels ready for custom construction', 'bi-map'),
(7, 'Studio Penthouse', 'penthouse', 'High-rise skyline suites with panoramic urban views', 'bi-stars');

-- 2. SEED USERS
-- Passwords below are hashed for 'Password123!'
INSERT INTO users (user_id, name, email, password, phone, role, status, email_verified, whatsapp_number, verification_status) VALUES
(1, 'EstateHub Admin', 'admin@estatehub.com', '$2a$10$vI8aWBnW3fID.ZQ4/zo1G.q1B7jB0K1w09S8lq1q1u4pL1G2w.3q2', '+18005550199', 'ADMIN', 'ACTIVE', TRUE, '+18005550199', 'VERIFIED'),
(2, 'Sarah Jenkins', 'sarah.seller@gmail.com', '$2a$10$vI8aWBnW3fID.ZQ4/zo1G.q1B7jB0K1w09S8lq1q1u4pL1G2w.3q2', '+14155552671', 'SELLER', 'ACTIVE', TRUE, '+14155552671', 'VERIFIED'),
(3, 'David Sterling', 'david.broker@estatehub.com', '$2a$10$vI8aWBnW3fID.ZQ4/zo1G.q1B7jB0K1w09S8lq1q1u4pL1G2w.3q2', '+14155558912', 'BROKER', 'ACTIVE', TRUE, '+14155558912', 'VERIFIED'),
(4, 'John Doe', 'john.customer@gmail.com', '$2a$10$vI8aWBnW3fID.ZQ4/zo1G.q1B7jB0K1w09S8lq1q1u4pL1G2w.3q2', '+14155553344', 'CUSTOMER', 'ACTIVE', TRUE, '+14155553344', 'UNVERIFIED'),
(5, 'Marcus Vance', 'marcus.unverified@gmail.com', '$2a$10$vI8aWBnW3fID.ZQ4/zo1G.q1B7jB0K1w09S8lq1q1u4pL1G2w.3q2', '+14155557766', 'SELLER', 'ACTIVE', TRUE, '+14155557766', 'PENDING'),
(6, 'Elena Rostova', 'elena.broker@luxury.com', '$2a$10$vI8aWBnW3fID.ZQ4/zo1G.q1B7jB0K1w09S8lq1q1u4pL1G2w.3q2', '+14155559988', 'BROKER', 'ACTIVE', TRUE, '+14155559988', 'VERIFIED');

-- 3. SEED VERIFICATION REQUESTS
INSERT INTO verification_requests (request_id, user_id, business_name, license_number, tax_id_or_pan, status, admin_notes, reviewed_by, reviewed_at) VALUES
(1, 2, 'Sarah Jenkins Private Portfolio', 'OWN-CA-9921', 'US-TAX-88912', 'APPROVED', 'Identity and property title verified by admin.', 1, NOW() - INTERVAL 10 DAY),
(2, 3, 'Sterling Realty & Capital Partners', 'RE-BRK-409182', 'US-TAX-44102', 'APPROVED', 'State broker board license active and verified in good standing.', 1, NOW() - INTERVAL 8 DAY),
(3, 5, 'Vance Holdings LLC', 'SELLER-DOC-112', 'US-TAX-99011', 'PENDING', 'Awaiting administrative document review.', NULL, NULL);

-- 4. SEED VERIFICATION DOCUMENTS
INSERT INTO verification_documents (document_id, request_id, document_type, file_path, original_file_name, file_size_kb) VALUES
(1, 1, 'GOVT_ID', 'uploads/verification/sarah_passport_scan.pdf', 'sarah_passport_scan.pdf', 1240),
(2, 1, 'PROPERTY_TITLE_DEED', 'uploads/verification/deed_oakridge_estate.pdf', 'deed_oakridge_estate.pdf', 3420),
(3, 2, 'BROKER_LICENSE', 'uploads/verification/sterling_realty_state_license.pdf', 'sterling_realty_state_license.pdf', 850),
(4, 2, 'BUSINESS_REGISTRATION', 'uploads/verification/sterling_llc_articles.pdf', 'sterling_llc_articles.pdf', 1980),
(5, 3, 'GOVT_ID', 'uploads/verification/marcus_driver_license.pdf', 'marcus_driver_license.pdf', 920);

-- 5. SEED PROPERTIES
INSERT INTO properties (property_id, user_id, category_id, title, description, price, location, city, state, purpose, area_sqft, bedrooms, bathrooms, furnishing, availability, property_status, verification_status, is_featured, view_count) VALUES
(1, 2, 2, 'Grand Pine Crest Luxury Villa', 'Spectacular Mediterranean modern villa featuring floor-to-ceiling glass walls, infinity heated pool, private manicured courtyard, custom chef kitchen, and smart home automation.', 1450000.00, '742 Evergreen Terrace, Pine Hill', 'San Francisco', 'CA', 'SALE', 4200.00, 4, 4, 'FULLY_FURNISHED', 'IMMEDIATE', 'AVAILABLE', 'VERIFIED', TRUE, 142),

(2, 3, 1, 'Skyline Panorama Bayview Residence', 'Upscale 27th-floor corner apartment overlooking the bay with designer quartz countertops, private wrap-around terrace, hardwood flooring, and 24/7 concierge valet.', 780000.00, '1088 Sansome Street, Waterfront', 'San Francisco', 'CA', 'SALE', 1650.00, 2, 2, 'FULLY_FURNISHED', 'IMMEDIATE', 'AVAILABLE', 'VERIFIED', TRUE, 98),

(3, 2, 3, 'Charming Craftsman Sunlit Duplex', 'Elegantly restored 3-bedroom craftsman home with sunroom, finished basement, solar power grid, custom cabinetry, and tranquil cedar wood rear deck.', 920000.00, '314 Maplewood Avenue, Elmhurst', 'San Francisco', 'CA', 'SALE', 2400.00, 3, 3, 'SEMI_FURNISHED', 'WITHIN_15_DAYS', 'AVAILABLE', 'VERIFIED', FALSE, 65),

(4, 3, 4, 'Financial Center Tech Hub Suite', 'Grade-A commercial office space with open collaborative bullpen, 4 executive glass breakout pods, high-speed fiber backbone, and private boardroom.', 12500.00, '555 California Street, Suite 1400', 'San Francisco', 'CA', 'RENT', 3800.00, 0, 4, 'FULLY_FURNISHED', 'IMMEDIATE', 'AVAILABLE', 'VERIFIED', FALSE, 44),

(5, 6, 7, 'The Luminary High-Rise Penthouse', 'Double-height ceiling penthouse with 360-degree metropolitan views, private rooftop dip pool, marble fireplace, private elevator access, and dual wine cellar.', 2850000.00, '200 Mission St, Penthouse 4B', 'San Francisco', 'CA', 'SALE', 5100.00, 5, 5, 'FULLY_FURNISHED', 'IMMEDIATE', 'AVAILABLE', 'VERIFIED', TRUE, 210),

(6, 3, 1, 'Urban Loft at Mission Heights', 'Industrial chic loft with exposed red brick, polished concrete floors, soaring 14-foot ceilings, automated roller blinds, and designated EV garage parking.', 3800.00, '820 Valencia Street, Unit 302', 'San Francisco', 'CA', 'RENT', 1150.00, 1, 1, 'SEMI_FURNISHED', 'IMMEDIATE', 'AVAILABLE', 'VERIFIED', FALSE, 83),

(7, 2, 6, 'Westridge Estates Hillside Parcel', 'Permitted residential land plot with panoramic scenic views of the valley. Approved architectural blueprints for a 4,500 sqft contemporary estate.', 520000.00, 'Lot 14, Westridge Ridge Road', 'San Jose', 'CA', 'SALE', 8500.00, 0, 0, 'UNFURNISHED', 'IMMEDIATE', 'AVAILABLE', 'VERIFIED', FALSE, 37),

(8, 5, 1, 'Pending Marina Bay Modern Condo', 'Bright waterside residence with marble bathrooms and yacht harbor outlook.', 690000.00, '410 Marina Blvd', 'San Francisco', 'CA', 'SALE', 1400.00, 2, 2, 'SEMI_FURNISHED', 'IMMEDIATE', 'AVAILABLE', 'PENDING', FALSE, 12);

-- 6. SEED PROPERTY IMAGES
INSERT INTO property_images (image_id, property_id, image_url, file_name, is_primary) VALUES
(1, 1, 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80', 'villa_front.jpg', TRUE),
(2, 1, 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80', 'villa_pool.jpg', FALSE),
(3, 1, 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80', 'villa_interior.jpg', FALSE),

(4, 2, 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80', 'apartment_skyline.jpg', TRUE),
(5, 2, 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80', 'apartment_living.jpg', FALSE),

(6, 3, 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80', 'house_exterior.jpg', TRUE),
(7, 3, 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80', 'house_kitchen.jpg', FALSE),

(8, 4, 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80', 'office_space.jpg', TRUE),
(9, 4, 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80', 'office_meeting.jpg', FALSE),

(10, 5, 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=80', 'penthouse_terrace.jpg', TRUE),
(11, 5, 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80', 'penthouse_master.jpg', FALSE),

(12, 6, 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80', 'loft_living.jpg', TRUE),
(13, 7, 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80', 'plot_land.jpg', TRUE),
(14, 8, 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80', 'marina_condo.jpg', TRUE);

-- 7. SEED USER PREFERENCES FOR CUSTOMER (User 4)
INSERT INTO user_preferences (preference_id, user_id, preferred_location, preferred_city, min_price, max_price, category_id, preferred_bedrooms, preferred_area_sqft, preferred_purpose) VALUES
(1, 4, 'San Francisco', 'San Francisco', 600000.00, 1600000.00, 2, 4, 3800.00, 'SALE');

-- 8. SEED FAVORITES
INSERT INTO favorites (favorite_id, user_id, property_id) VALUES
(1, 4, 1),
(2, 4, 2);

-- 9. SEED INQUIRIES
INSERT INTO inquiries (inquiry_id, property_id, customer_id, message, contact_phone, preferred_visit_date, status, seller_reply, replied_at) VALUES
(1, 1, 4, 'Hello Sarah, I am very interested in this luxury villa. Is the solar grid fully owned or leased, and can we schedule an in-person walkthrough this Saturday afternoon?', '+14155553344', '2026-09-06', 'RESPONDED', 'Hi John! The solar array is 100% owned with warranty. Saturday at 2:00 PM works perfectly for the tour.', NOW() - INTERVAL 1 DAY),
(2, 2, 4, 'Hi David, what are the monthly HOA fees and what amenities are covered in the building?', '+14155553344', '2026-09-08', 'OPEN', NULL, NULL);

-- 10. SEED CONVERSATIONS & MESSAGES
INSERT INTO conversations (conversation_id, property_id, customer_id, provider_id, status) VALUES
(1, 1, 4, 2, 'ACTIVE');

INSERT INTO messages (message_id, conversation_id, sender_id, message_text, is_read, created_at) VALUES
(1, 1, 4, 'Hello Sarah, does the villa come with the built-in sound system installed?', TRUE, NOW() - INTERVAL 4 HOUR),
(2, 1, 2, 'Yes John! The Sonos integrated acoustic ceiling system is included across all 4 bedrooms and outdoor patio.', TRUE, NOW() - INTERVAL 3 HOUR),
(3, 1, 4, 'That sounds wonderful. I look forward to Saturday walkthrough.', FALSE, NOW() - INTERVAL 1 HOUR);

-- 11. SEED RECENT VIEWS
INSERT INTO property_views (view_id, user_id, property_id, ip_address, viewed_at) VALUES
(1, 4, 1, '127.0.0.1', NOW() - INTERVAL 3 HOUR),
(2, 4, 2, '127.0.0.1', NOW() - INTERVAL 2 HOUR),
(3, 4, 3, '127.0.0.1', NOW() - INTERVAL 1 HOUR);
